# Generated by Django 5.2.8 on 2025-11-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_librarymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("author", models.CharField()),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
