# Generated by Django 5.2.8 on 2025-11-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_bookmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
