# Generated by Django 5.2.8 on 2025-11-10 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0004_alter_bookmodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmodel",
            name="lib_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.signupmodel",
            ),
            preserve_default=False,
        ),
    ]
