# Generated by Django 5.2.8 on 2025-11-10 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0005_bookmodel_lib_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="lib_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.signupmodel",
            ),
        ),
    ]
