# Generated by Django 5.2.8 on 2025-11-11 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0006_alter_bookmodel_lib_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddDetailsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("education", models.CharField(blank=True, max_length=100)),
                ("section", models.CharField(blank=True, max_length=50)),
                ("DOB", models.DateField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                (
                    "read_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="my_app.signupmodel",
                    ),
                ),
            ],
        ),
    ]
