# Generated by Django 5.2.8 on 2025-11-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0007_adddetailsmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AddDetailsModel",
        ),
    ]
