# Generated by Django 5.2.8 on 2025-11-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0008_delete_adddetailsmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signupmodel",
            name="confirm_password",
        ),
        migrations.AddField(
            model_name="signupmodel",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="signupmodel",
            name="password",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="signupmodel",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
